version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels: []
    ignore:
      - dependency-name: "com.zaxxer:HikariCP"
        versions:
          - ">=5.0.0"
      - dependency-name: "architectury-plugin"
      - dependency-name: "dev.architectury.loom-no-remap"
      - dependency-name: "net.neoforged:neoforge"
      - dependency-name: "net.fabricmc:fabric-loader"
