modLoader = "kotlinforforge"
loaderVersion="[5.10,)"
license = "AGPL-3.0-or-later"
issueTrackerURL = "https://github.com/kenshineto/kenshinshideandseek/issues"

[[mods]]
modId = "khs"
version = "${version}"
displayName = "${name}"
authors = "${author}"
description = "Minecrafts Best Hide and Seek and Block Hunt Mod"
logoFile = "assets/logo.png"

[[mixins]]
config = "khs.mixins.json"

[[dependencies.khs]]
modId = "neoforge"
type = "required"
versionRange = "[${minecraft},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.khs]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.khs]]
modId = "architectury"
type = "required"
versionRange = "[${architectury},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.khs]]
modId = "packetevents"
type = "required"
versionRange = "[${packetevents},)"
ordering = "AFTER"
side = "BOTH"
