import org.gradle.api.Project
import org.gradle.api.Task
import org.gradle.api.artifacts.VersionCatalog
import org.gradle.api.artifacts.VersionCatalogsExtension
import org.gradle.api.tasks.TaskProvider

fun readPermissionsFile(): String {
    val ins = object {}.javaClass.getResourceAsStream("/permissions.yml")
    return ins?.bufferedReader()?.use { it.readText() } ?: error("failed to read permissions")
}

fun Project.getVersion(name: String): String {
    val libs = extensions
        .getByType(VersionCatalogsExtension::class.java)
        .named("libs")

    return libs.findVersion(name).get().requiredVersion.replace(".+", "")
}

fun Project.getBuildInfo(): Map<String, Any> = mapOf(
    // meta
    "id" to rootProject.name,
    "version" to rootProject.version.toString(),
    "name" to providers.gradleProperty("khs.name").get(),
    "author" to providers.gradleProperty("khs.author").get(),

    // dependencies
    "minecraft" to getVersion("minecraft"),
    "fabricloader" to getVersion("fabric-loader"),
    "packetevents" to getVersion("packetevents"),
    "architectury" to getVersion("architectury"),

    // telemetry
    "telemetry" to providers.gradleProperty("khs.telemetry").map(String::toBoolean).getOrElse(false),
    "bstatsId" to providers.gradleProperty("khs.bstatsId").map(String::toIntOrNull).getOrElse(0),
)

fun Project.getTemplateVars(): Map<String, Any> = mapOf(
    // permissions
    "permissions" to readPermissionsFile()
) + getBuildInfo()

fun Project.registerBuildInfoTask(): TaskProvider<Task> {
    val output = layout.buildDirectory.dir("generated/sources/buildInfo/kotlin")
    val buildInfo = rootProject.getBuildInfo()
    val packageName = rootProject.group.toString()

    val task = tasks.register("generateBuildInfo") {
        outputs.dir(output)

        doLast {
            val packageDir = output.get().asFile.resolve(packageName.replace('.', '/'))
            packageDir.mkdirs()

            packageDir.resolve("BuildInfo.kt").writeText(buildString {
                appendLine("package $packageName")
                appendLine("/** Generated by Gradle. DO NOT EDIT. */")
                appendLine("object BuildInfo {")

                buildInfo.forEach { (key, value) ->
                    appendLine("    const val ${key} = ${value.toKotlinLiteral()}")
                }

                appendLine("}")
            })
        }
    }

    return task
}

private fun Any?.toKotlinLiteral(): String =
    when (this) {
        null -> "null"
        is String -> "\"${this}\""
        is Number, is Boolean -> toString()
        else -> "\"${toString()}\""
    }
