package cat.freya.khs.config

import cat.freya.khs.world.World

data class WorldConfig(var type: World.Type = World.Type.NORMAL)

data class KhsWorldsConfig(
    @Comment("DO NOT EDIT THIS FILE - It is autogenerated")
    @Comment("Please use /hs world ... commands instead")
    var worlds: MutableMap<String, WorldConfig> = mutableMapOf()
) {
    fun update(name: String, fn: WorldConfig.() -> Unit) {
        val config = worlds.get(name) ?: WorldConfig()
        fn(config)
        worlds[name] = config
    }
}
