name: "${id}"
main: "cat.freya.khs.bukkit.KhsPlugin"
version: "${version}"
author: "${author}"
website: "freya.cat"
load: "STARTUP"
api-version: ${minecraft}

dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false

${permissions}
