name: "${id}"
main: "cat.freya.khs.bukkit.KhsPlugin"
version: "${version}"
author: "${author}"
website: "freya.cat"
load: "STARTUP"
api-version: 1.13
depend:
  - "packetevents"
softdepend:
  - "PlaceholderAPI"

${permissions}
